### ISSUE TITLE
Manage suppliers

### ISSUE THREAD

**Issue by DrunkenToast** [tm-pe2/ad-website#15]
- [ ] View Supplier in website
       -  View Group
       - Address
       - Name
       - Other Supplier stuff
- [ ] Add / Delete / Edit Suppliers
       -  work with permissions (EXAMPLE: Worker can Add not Delete / Admin can Add, Delete but not edit)
- [ ] Filter Suppliers
       - Filter group
       - Filter ACD / DECS
       - Filter City / Country
- [ ] Put Suppliers in groups

**Comment by KilliBruhh** [comment]
Splittet the task up in 3 seperate tasks
