### ISSUE TITLE
Set design standards

### ISSUE THREAD

**Issue by DrunkenToast** [tm-pe2/ad-website#29]
In Tailwind css config you can set standards such as colors.
Examples:

- Primary color
- Secondary color
- Accent color
- Dark/light mode?
- Margins/paddings
- heights
- ...

**Comment by Dries1234** [comment]
As indicated by the tag, this looks like a good issue for anyone who doesn't know what to do when they are out of tasks.

**Comment by DrunkenToast** [comment]
@Marten3004 You might be interested in this task

**Comment by Marten3004** [comment]
@DrunkenToast I think its best that I take this after the first sprint when we are really adding the right style to each page. Now I don't really have an idea of what the webpages will look like with the header and footer included.
